In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("/Users/mohammadabdulmuneermognishaik/Documents/Projects/stock-market-data-pipeline/database/stock.db")

In [2]:
cursor = conn.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

print("Tables in database:")
for t in tables:
    print("-", t[0])

Tables in database:
- stock_prices
- interest_rates
- inflation
- vix
- qqq
- oil
- Gas

# Column Rename stock_prices or MSFT

In [3]:
msft = pd.read_sql("SELECT * FROM stock_prices", conn)
msft.columns

Index(['Price', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')

In [4]:
msft = msft.rename(columns={
    "Close": "MSFT_Close",
    "High": "MSFT_High",
    "Low": "MSFT_Low",
    "Open": "MSFT_Open",
    "Volume": "MSFT_Volume",
    "Price": "MSFT_Date"
})

In [5]:
msft.columns

Index(['MSFT_Date', 'MSFT_Close', 'MSFT_High', 'MSFT_Low', 'MSFT_Open',
       'MSFT_Volume'],
      dtype='str')

# Column rename interest_rates

In [6]:
interest_rates = pd.read_sql("SELECT * FROM interest_rates", conn)
interest_rates.columns

Index(['Date', 'InterestRate'], dtype='str')

In [7]:
interest_rates = interest_rates.rename(columns={
    "Date": "InterestRate_Date",
    "InterestRate": "Interest_Rate",
})

In [8]:
interest_rates.columns

Index(['InterestRate_Date', 'Interest_Rate'], dtype='str')

In [9]:
# INFLATION

inflation = pd.read_sql("SELECT * FROM inflation", conn)
inflation.columns

Index(['Date', 'Inflation'], dtype='str')

In [10]:
inflation = inflation.rename(columns={
    "Date": "inflation_Date",
})

In [11]:
inflation.columns

Index(['inflation_Date', 'Inflation'], dtype='str')

In [12]:
# VIX (FEAR INDEX)

vix = pd.read_sql("SELECT * FROM vix", conn)
vix.columns

Index(['Price', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')

In [13]:
vix = vix.rename(columns={
    "Close": "vix_Close",
    "High": "vix_High",
    "Low": "vix_Low",
    "Open": "vix_Open",
    "Volume": "vix_Volume",
    "Price": "vix_Date"
})

In [14]:
vix.columns

Index(['vix_Date', 'vix_Close', 'vix_High', 'vix_Low', 'vix_Open',
       'vix_Volume'],
      dtype='str')

In [15]:
# QQQ (TECH SENTIMENT)

qqq = pd.read_sql("SELECT * FROM qqq", conn)
qqq.columns

Index(['Price', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')

In [16]:
qqq = qqq.rename(columns={
    "Close": "qqq_Close",
    "High": "qqq_High",
    "Low": "qqq_Low",
    "Open": "qqq_Open",
    "Volume": "qqq_Volume",
    "Price": "qqq_Date"
})

In [17]:
qqq.columns

Index(['qqq_Date', 'qqq_Close', 'qqq_High', 'qqq_Low', 'qqq_Open',
       'qqq_Volume'],
      dtype='str')

In [18]:
# OIL

oil = pd.read_sql("SELECT * FROM oil", conn)
oil.columns

Index(['Price', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')

In [19]:
oil = oil.rename(columns={
    "Close": "oil_Close",
    "High": "oil_High",
    "Low": "oil_Low",
    "Open": "oil_Open",
    "Volume": "oil_Volume",
    "Price": "oil_Date"
})

In [20]:
oil.columns

Index(['oil_Date', 'oil_Close', 'oil_High', 'oil_Low', 'oil_Open',
       'oil_Volume'],
      dtype='str')

In [21]:
# GAS
gas = pd.read_sql("SELECT * FROM gas", conn)
gas.columns

Index(['Price', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')

In [22]:
gas = gas.rename(columns={
    "Close": "gas_Close",
    "High": "gas_High",
    "Low": "gas_Low",
    "Open": "gas_Open",
    "Volume": "gas_Volume",
    "Price": "gas_Date"
})

In [23]:
gas.columns

Index(['gas_Date', 'gas_Close', 'gas_High', 'gas_Low', 'gas_Open',
       'gas_Volume'],
      dtype='str')

In [24]:
msft.columns, interest_rates.columns, inflation.columns, vix.columns, qqq.columns, oil.columns, gas.columns

(Index(['MSFT_Date', 'MSFT_Close', 'MSFT_High', 'MSFT_Low', 'MSFT_Open',
        'MSFT_Volume'],
       dtype='str'),
 Index(['InterestRate_Date', 'Interest_Rate'], dtype='str'),
 Index(['inflation_Date', 'Inflation'], dtype='str'),
 Index(['vix_Date', 'vix_Close', 'vix_High', 'vix_Low', 'vix_Open',
        'vix_Volume'],
       dtype='str'),
 Index(['qqq_Date', 'qqq_Close', 'qqq_High', 'qqq_Low', 'qqq_Open',
        'qqq_Volume'],
       dtype='str'),
 Index(['oil_Date', 'oil_Close', 'oil_High', 'oil_Low', 'oil_Open',
        'oil_Volume'],
       dtype='str'),
 Index(['gas_Date', 'gas_Close', 'gas_High', 'gas_Low', 'gas_Open',
        'gas_Volume'],
       dtype='str'))

In [25]:
msft.head(10)

,MSFT_Date,MSFT_Close,MSFT_High,MSFT_Low,MSFT_Open,MSFT_Volume
0,Ticker,MSFT,MSFT,MSFT,MSFT,MSFT
1,Date,NaN,NaN,NaN,NaN,NaN
2,2024-04-25,393.0078430175781,393.8449998393028,382.16426819567243,388.0735680343126,40586500
3,2024-04-26,400.1778259277344,406.7568397543272,399.6262936342629,405.93939976601416,29694700
4,2024-04-29,396.1693115234375,400.17779380940664,393.1555709987601,399.12396145400385,19582100
5,2024-04-30,383.444580078125,396.0806489273893,383.28702520862055,395.42076392930267,28781400
6,2024-05-01,388.9698181152344,395.6473257764034,384.4098035661703,386.6750231640028,23562500
7,2024-05-02,391.82598876953125,393.88439136644655,388.6842084752251,391.6487169798458,17709400
8,2024-05-03,400.51263427734375,400.99521746175435,395.7851765465019,396.1988407447482,17446700
9,2024-05-06,407.2886962890625,407.67278519206855,400.2270689712312,402.5809547625938,16996600

In [26]:
msft = msft.rename(columns={"MSFT_Date": "Date"})
interest_rates = interest_rates.rename(columns={"InterestRate_Date": "Date"})
inflation = inflation.rename(columns={"inflation_Date": "Date"})
vix = vix.rename(columns={"vix_Date": "Date"})
qqq = qqq.rename(columns={"qqq_Date": "Date"})
oil = oil.rename(columns={"oil_Date": "Date"})
gas = gas.rename(columns={"gas_Date": "Date"})

In [27]:
datasets = {
    "msft": msft,
    "vix": vix,
    "qqq": qqq,
    "interest_rates": interest_rates,
    "inflation": inflation,
    "oil": oil,
    "gas": gas
}

In [28]:
for name, df in datasets.items():
    print("\n", name)
    print(df.columns)

 msft
Index(['Date', 'MSFT_Close', 'MSFT_High', 'MSFT_Low', 'MSFT_Open',
       'MSFT_Volume'],
      dtype='str')

 vix
Index(['Date', 'vix_Close', 'vix_High', 'vix_Low', 'vix_Open', 'vix_Volume'], dtype='str')

 qqq
Index(['Date', 'qqq_Close', 'qqq_High', 'qqq_Low', 'qqq_Open', 'qqq_Volume'], dtype='str')

 interest_rates
Index(['Date', 'Interest_Rate'], dtype='str')

 inflation
Index(['Date', 'Inflation'], dtype='str')

 oil
Index(['Date', 'oil_Close', 'oil_High', 'oil_Low', 'oil_Open', 'oil_Volume'], dtype='str')

 gas
Index(['Date', 'gas_Close', 'gas_High', 'gas_Low', 'gas_Open', 'gas_Volume'], dtype='str')

In [29]:
inflation.head(10)

         Date  Inflation
0  1947-01-01      21.48
1  1947-02-01      21.62
2  1947-03-01      22.00
3  1947-04-01      22.00
4  1947-05-01      21.95
5  1947-06-01      22.08
6  1947-07-01      22.23
7  1947-08-01      22.40
8  1947-09-01      22.84
9  1947-10-01      22.91

In [30]:
skip_first_two = ["msft", "vix", "qqq", "oil", "gas"]

for name, df in datasets.items():
    if name in skip_first_two:
        df = df.iloc[2:].reset_index(drop=True)
        datasets[name] = df

In [31]:
msft = datasets["msft"]
vix = datasets["vix"]
qqq = datasets["qqq"]
oil = datasets["oil"]
gas = datasets["gas"]

In [ ]:
print(msft.head())
print(vix.head())
print(qqq.head())

         Date         MSFT_Close           MSFT_High            MSFT_Low  \
0  2024-04-25  393.0078430175781   393.8449998393028  382.16426819567243
1  2024-04-26  400.1778259277344   406.7568397543272   399.6262936342629
2  2024-04-29  396.1693115234375  400.17779380940664   393.1555709987601
3  2024-04-30   383.444580078125   396.0806489273893  383.28702520862055
4  2024-05-01  388.9698181152344   395.6473257764034   384.4098035661703

            MSFT_Open MSFT_Volume
0   388.0735680343126    40586500
1  405.93939976601416    29694700
2  399.12396145400385    19582100
3  395.42076392930267    28781400
4   386.6750231640028    23562500
         Date           vix_Close            vix_High             vix_Low  \
0  2024-04-24  15.970000267028809    16.3799991607666  15.579999923706055
1  2024-04-25  15.369999885559082  17.549999237060547  15.270000457763672
2  2024-04-26  15.029999732971191  16.059999465942383  14.920000076293945
3  2024-04-29  14.670000076293945  15.420000076293945  14.630000114440918
4  2024-04-30  15.649999618530273  15.899999618530273  14.670000076293945

             vix_Open vix_Volume
0  15.760000228881836          0
1               16.25          0
2  15.489999771118164          0
3  15.369999885559082          0
4  14.819999694824219          0
         Date           qqq_Close            qqq_High             qqq_Low  \
0  2024-04-25   419.8391418457031   420.6996860627022  413.59769082942586
1  2024-04-26   426.3179931640625  427.85114324602824  422.28232799555997
2  2024-04-29   428.0489807128906  429.04801861164475  425.30908244856215
3  2024-04-30  419.97760009765625   427.8610217852048   419.8984824336748
4  2024-05-01  416.94097900390625   425.4673645155584  416.09033575149846

             qqq_Open qqq_Volume
0   414.6857171994804   57392200
1   422.9747056964863   41874900
2  428.42485755345405   30022200
3  426.46633524230674   43665900
4   418.5532769953046   52251700
         Date          oil_Close           oil_High            oil_Low  \
0  2024-04-26   83.8499984741211  84.45999908447266   83.3499984741211
1  2024-04-29  82.62999725341797  83.91000366210938   82.4000015258789
2  2024-04-30  81.93000030517578  83.30000305175781  80.94999694824219
3  2024-05-01               79.0  81.56999969482422  78.83000183105469
4  2024-05-02  78.94999694824219   79.9000015258789  78.41000366210938

            oil_Open oil_Volume
0  83.80999755859375     244090
1  83.69000244140625     336984
2  82.76000213623047     400680
3   81.4800033569336     441978
4   79.1500015258789     359652
         Date           gas_Close            gas_High             gas_Low  \
0  2024-04-26  1.6139999628067017   1.628000020980835  1.4819999933242798
1  2024-04-29  2.0299999713897705   2.055999994277954  1.9160000085830688
2  2024-04-30  1.9910000562667847  2.0920000076293945  1.9509999752044678
3  2024-05-01  1.9320000410079956  1.9700000286102295  1.9129999876022339
4  2024-05-02  2.0350000858306885   2.049999952316284  1.9270000457763672

             gas_Open gas_Volume
0   1.621999979019165     119516
1  1.9229999780654907     158855
2   2.049999952316284     150370
3  1.9539999961853027     135918
4   1.930999994277954     153739

In [33]:
print(oil.head())
print(gas.head())

         Date          oil_Close           oil_High            oil_Low  \
0  2024-04-26   83.8499984741211  84.45999908447266   83.3499984741211
1  2024-04-29  82.62999725341797  83.91000366210938   82.4000015258789
2  2024-04-30  81.93000030517578  83.30000305175781  80.94999694824219
3  2024-05-01               79.0  81.56999969482422  78.83000183105469
4  2024-05-02  78.94999694824219   79.9000015258789  78.41000366210938

            oil_Open oil_Volume
0  83.80999755859375     244090
1  83.69000244140625     336984
2  82.76000213623047     400680
3   81.4800033569336     441978
4   79.1500015258789     359652
         Date           gas_Close            gas_High             gas_Low  \
0  2024-04-26  1.6139999628067017   1.628000020980835  1.4819999933242798
1  2024-04-29  2.0299999713897705   2.055999994277954  1.9160000085830688
2  2024-04-30  1.9910000562667847  2.0920000076293945  1.9509999752044678
3  2024-05-01  1.9320000410079956  1.9700000286102295  1.9129999876022339
4  2024-05-02  2.0350000858306885   2.049999952316284  1.9270000457763672

             gas_Open gas_Volume
0   1.621999979019165     119516
1  1.9229999780654907     158855
2   2.049999952316284     150370
3  1.9539999961853027     135918
4   1.930999994277954     153739